/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dy_dwvm_mt_MTLib_MTLibCallback */

#ifndef _Included_com_dy_dwvm_mt_MTLib_MTLibCallback
#define _Included_com_dy_dwvm_mt_MTLib_MTLibCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
